appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Kf3OcbVjx2KlQP5uYo66BHFxq3Tj1VEI81Egh1k4odpGA6xiS0+yUNBhNmYxQ2YlmLoKnMH67BcoU09lZcPWgn1wQQ9w8hFCoxmXrK4QVu59Y/xucUugyeb73eDc4ncB2FqrP58SL5m12b4rBICXWznN2xB6lo9+jOzDLQ+AqbZ4KzzL0NQVDuCAS7KlwYOQP+HjZZ6C+Bv2arwcclGRocaMtU0R7LB1T5728vsdp2mPyzQYfXYulVWHuWXgCnmTWfT7X8wnVoq8Y5zoY0lRCeqQck6lJswBJB4+kk6lTyXr3b0oS9N3ZbGlipgkSo2U1HLDFh9/nGSiUCr7WZaIz4wWSEmLkqQfLDEA4T7e/eLmokgg+aFFNYMIQqHVwvgmgk/qqV6sQYFuEoTrl7JQtd8KTjzwagWNobQ3iVQF6OCnGUgvRQ8l5FfCnDLzYQKuonbadDoa4egBhuPs+wIEJWD9MO2ojtmbIUX5SmunindlYJeMKkxmNn6bovpM2LcK0CU6yaF3D1oEbcS1TpSniegeexXn7NeqgYo1/js0ouY6yO6XzwnkOyNQCgi5HPQjHMZVlcR8VXby2k6r7qys1mrra6KG/iu8uwD7rdpZRZVeCjuNNyUQK8YSv0MDe2XZ/5qSMys2++M0pEeHKkd/ZgZN79+PPdcKPGMeoGzPAzY=}
